version: 0.2

env:
  parameter-store:
    # API_KEY: /slackbot/ApiKey
    AI_MODEL_ID: /slackbotgo/AiModelId
    CHANNEL_ID: /slackbotgo/ChannelId
    SIGNING_SECRET: /slackbotgo/SigningSecret
    OAUTH_TOKEN: /slackbotgo/OAuthToken

phases:
  install:
    runtime-versions:
      golang: 1.26
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Build phase"
      - sam build
  post_build:
    commands:
      - echo "Post-build phase"
      - sam deploy --stack-name slackbot-go --region ap-northeast-1 --parameter-overrides AiModelId=${AI_MODEL_ID} ChannelId=${CHANNEL_ID} SigningSecret=${SIGNING_SECRET} OAuthToken=${OAUTH_TOKEN} --no-confirm-changeset --no-fail-on-empty-changeset
      # - sam deploy --stack-name slackbot-go --region ap-northeast-1 --parameter-overrides ApiKey=${API_KEY} ChannelId=${CHANNEL_ID} SigningSecret=${SIGNING_SECRET} OAuthToken=${OAUTH_TOKEN} --no-confirm-changeset --no-fail-on-empty-changeset

# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-spec-ref.html
