version: 0.2

env:
  parameter-store:
    API_KEY: /slackbot/ApiKey
    CHANNEL_ID: /slackbot/ChannelId
    SIGNING_SECRET_GPT3: /slackbot/SigningSecret/GPT3
    OAUTH_TOKEN_GPT3: /slackbot/OAuthToken/GPT3
    SIGNING_SECRET_GPT4: /slackbot/SigningSecret/GPT4
    OAUTH_TOKEN_GPT4: /slackbot/OAuthToken/GPT4
    SIGNING_SECRET_CLAUDE1: /slackbot/SigningSecret/Claude1
    OAUTH_TOKEN_CLAUDE1: /slackbot/OAuthToken/Claude1
    SIGNING_SECRET_CLAUDE2: /slackbot/SigningSecret/Claude2
    OAUTH_TOKEN_CLAUDE2: /slackbot/OAuthToken/Claude2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Build phase"
      - sam build
  post_build:
    commands:
      - echo "Post-build phase"
      - sam deploy --stack-name slackbot-go --region ap-northeast-1 --parameter-overrides ApiKey=${API_KEY} ChannelId=${CHANNEL_ID} SigningSecretGPT3=${SIGNING_SECRET_GPT3} OAuthTokenGPT3=${OAUTH_TOKEN_GPT3} SigningSecretGPT4=${SIGNING_SECRET_GPT4} OAuthTokenGPT4=${OAUTH_TOKEN_GPT4} SigningSecretClaude1=${SIGNING_SECRET_CLAUDE1} OAuthTokenClaude1=${OAUTH_TOKEN_CLAUDE1} SigningSecretClaude2=${SIGNING_SECRET_CLAUDE2} OAuthTokenClaude2=${OAUTH_TOKEN_CLAUDE2} --no-confirm-changeset --no-fail-on-empty-changeset

# https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-spec-ref.html
