AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slackbot-go
  SAM Template for slackbot-go

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: bootstrap
    Runtime: provided.al2023
    CodeUri: src/
    MemorySize: 256
    Timeout: 180
    Environment:
      Variables:
        AI_MODEL_PROVIDER: 'anthropic'
        AI_MODEL_ID: !Ref AiModelId
        SLACK_CHANNEL_ID: !Ref ChannelId
        SLACK_API_SIGNING_SECRET: !Ref SigningSecret
        SLACK_BOT_OAUTH_TOKEN: !Ref OAuthToken
    Tracing: Active
    Architectures:
      - x86_64

Parameters:
  AiModelId:
    Type: String
    Description: Bedrockで有効化しているモデルID、または推論プロファイルID
  ChannelId:
    Type: String
    NoEcho: true
  SigningSecret:
    Type: String
    NoEcho: true
  OAuthToken:
    Type: String
    NoEcho: true

Resources:
  GoHiyokoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: slackbot-go-GoHiyokoFunction
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource:
                - 'arn:aws:bedrock:*::foundation-model/*'
                - !Sub 'arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/*'
  GoHiyokoResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub 'ApplicationInsights-SAM-${AWS::StackName}'
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  GoHiyokoInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      AutoConfigurationEnabled: true
      ResourceGroupName: !Ref GoHiyokoResourceGroup
Outputs:
  GoHiyokoFunctionUrl:
    Description: "GoHiyokoFunction URLs endpoint"
    Value: !GetAtt GoHiyokoFunctionUrl.FunctionUrl
